# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm7125-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter nasha RMX2170 RMX2061,$(TARGET_DEVICE)),)

endif
